name: 🚀 Deploy to Staging

on:
  workflow_run:
    workflows: [ Laravel ]
    branches: [ main ]
    types:
      - completed

jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Install Github Action Checkout
        uses: actions/checkout@v2

      - name: 🖥️ Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/stocktake/web
            php artisan down
            git fetch --all
            git reset --hard origin/main
            git pull
            sudo chmod -R ug+rwx storage bootstrap/cache
            sudo chmod -R g+w storage/logs
            sudo php artisan optimize:clear
            php artisan view:clear
            npm i --silent
            composer i -o -n --no-dev
            php artisan cloudflare:reload
            php artisan optimize
            php artisan view:cache
            npm run prod --silent
            sudo service redis-server restart
            sudo supervisorctl restart stocktake-web-cron:stocktake-web-cron_00
            sudo supervisorctl restart stocktake-web-worker:stocktake-web-worker_00
            sudo supervisorctl restart stocktake-web-worker:stocktake-web-worker_01
            sudo supervisorctl restart stocktake-web-worker:stocktake-web-worker_02
            sudo supervisorctl restart stocktake-web-worker:stocktake-web-worker_03
            sudo supervisorctl restart stocktake-web-worker:stocktake-web-worker_04
            sudo supervisorctl restart stocktake-web-worker:stocktake-web-worker_05
            sudo supervisorctl restart stocktake-web-worker:stocktake-web-worker_06
            sudo supervisorctl restart stocktake-web-worker:stocktake-web-worker_07
            sudo php artisan octane:reload
            sudo rm -rf /var/cache/ngx_pagespeed/*
            php artisan env
            php artisan up
