name: 🗃️ Deploy Migration to Production

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Install Github Action Checkout
        uses: actions/checkout@v2

      - name: 🖥️ Deploy Migration using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/stocktake/web
            php artisan down
            git branch --set-upstream-to=origin/main
            git fetch --all
            git reset --hard origin/main
            git pull
            sudo chgrp -R www-data storage bootstrap/cache
            sudo chmod -R ug+rwx storage bootstrap/cache
            sudo chmod -R g+w storage/logs
            composer i -o -n --no-dev
            php artisan migrate:fresh --seed --force
            php artisan env
            php artisan up
